/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VistaGFichaTitulo.java
 *
 * Created on 26-nov-2011, 17:38:02
 */
package Vista.Nivel2;

import Controlador.Controlador;
import Controlador.Evento;
import Controlador.GestorEventos;
import Controlador.TipoEvento;
import HBM.Autor;
import HBM.Dewey;
import HBM.Idioma6391;
import HBM.Titulo;
import HBM.TituloId;
import Vista.Modelos.BaseTableModelGen;
import java.beans.PropertyChangeEvent;
import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.lang3.text.WordUtils;

/**
 *
 * @author nanohp
 */
public class VistaGFichaTitulo extends FichaGBase {

    Titulo titulo;
    List<Dewey> listaCategoriasDewey;
    List<Idioma6391> listaIdiomas6391;
    AutoresTableModel autoresTableModel;
    private Controlador controlador;
    private String modo;

    /** Creates new form VistaGFichaTitulo */
    public VistaGFichaTitulo(Controlador controlador, List<Dewey> listaCategoriasDewey, List<Idioma6391> listaIdiomas6391) {
        this.listaCategoriasDewey = listaCategoriasDewey;
        this.listaIdiomas6391 = listaIdiomas6391;
        initComponents();
        inicializaComponentesPropios();
        this.controlador = controlador;
    }

    public VistaGFichaTitulo(Controlador controlador, List<Dewey> listaCategoriasDewey, List<Idioma6391> listaIdiomas6391, GestorEventos padre) {
        this.listaCategoriasDewey = listaCategoriasDewey;
        this.listaIdiomas6391 = listaIdiomas6391;
        initComponents();
        inicializaComponentesPropios();
        this.controlador = controlador;
        setDelegado(padre);
    }

    private void inicializaComponentesPropios() {
        jComboBoxCodDewey.addItem("Seleccione categoría");
        for (Dewey dewey : listaCategoriasDewey) {
            //jComboBoxCodDewey.addItem(dewey.getCategoriaDewey() + " - " + dewey.getNombreCategoriaDewey());
            jComboBoxCodDewey.addItem(dewey);
        }

        jComboBoxIdiomas6391.removeAllItems();
        jComboBoxIdiomas6391.addItem("Seleccione idioma");
        for (Idioma6391 idioma6391 : listaIdiomas6391) {
            jComboBoxIdiomas6391.addItem(idioma6391);
        }
    }

    public void setTitulo(Titulo titulo) {
        jTextFieldNombre.setText(titulo.getNombreTitulo());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAutores = new javax.swing.JTable();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldCodTitulo = new javax.swing.JTextField();
        jButtonAceptar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCodAutor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaSinopsis = new javax.swing.JTextArea();
        jComboBoxCodDewey = new javax.swing.JComboBox();
        jLabelPaginasTitulo = new javax.swing.JLabel();
        jTextFieldNumPaginas = new javax.swing.JTextField();
        jLabelFechaAdquisicion = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jDateChooserFechaAdquisicion = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxIdiomas6391 = new javax.swing.JComboBox();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ficha título");

        jLabel2.setText("Nombre");

        jLabel3.setText("Autores");

        jTableAutores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Apellidos", "Autor"
            }
        ));
        jScrollPane1.setViewportView(jTableAutores);

        jTextFieldNombre.setColumns(30);
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });

        jTextFieldCodTitulo.setColumns(3);

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jLabel4.setText("Dewey");

        jTextFieldCodAutor.setColumns(3);

        jLabel5.setText("Sinopsis");

        jTextAreaSinopsis.setColumns(20);
        jTextAreaSinopsis.setLineWrap(true);
        jTextAreaSinopsis.setRows(5);
        jTextAreaSinopsis.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextAreaSinopsis);

        jComboBoxCodDewey.setModel(new javax.swing.DefaultComboBoxModel());

        jLabelPaginasTitulo.setText("Páginas");

        jLabelFechaAdquisicion.setText("Fecha Adq.");

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Idioma");

        jComboBoxIdiomas6391.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(495, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxCodDewey, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCodAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCodTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldNumPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxIdiomas6391, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE))
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPaginasTitulo)
                .addContainerGap(497, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jButtonAceptar)
                .addGap(77, 77, 77)
                .addComponent(jButtonCancelar)
                .addContainerGap(196, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(275, Short.MAX_VALUE)
                .addComponent(jLabelFechaAdquisicion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooserFechaAdquisicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxCodDewey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCodAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCodTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPaginasTitulo)
                    .addComponent(jTextFieldNumPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxIdiomas6391, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDateChooserFechaAdquisicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel3))
                    .addComponent(jLabelFechaAdquisicion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptar)
                    .addComponent(jButtonCancelar))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed

        if (modo.equalsIgnoreCase("mostrar")) {
            setVisible(false);
        } else if (modo.equalsIgnoreCase("modificar")) {
            titulo.setSinopsis(jTextAreaSinopsis.getText());

            try {
                titulo.setNumPaginas(Short.parseShort(jTextFieldNumPaginas.getText()));
            } catch (NumberFormatException nFormatException) {
                System.err.println("Numero de paginas incorrecto");
            }
            titulo.setFechaAdquisicion(jDateChooserFechaAdquisicion.getDate());
            titulo.setIdioma6391((Idioma6391) jComboBoxIdiomas6391.getSelectedItem());
            Evento evento = new Evento(TipoEvento.MODIFICACION_TITULO, titulo, this);
            controlador.procesarEvento(evento);
        } else if (modo.equalsIgnoreCase("baja")) {

            String cadena = titulo.toString();
            String mensaje = "¿Desea borrar el título?";
            String tituloStr = "Borrado de título: " + cadena;

            int respuetaInt = JOptionPane.showConfirmDialog(null, mensaje, tituloStr, JOptionPane.YES_NO_OPTION);
            if (respuetaInt == JOptionPane.YES_OPTION) {
                Evento evento = new Evento(TipoEvento.BAJA_TITULO, titulo, this);
                controlador.procesarEvento(evento);
            }
        }
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JComboBox jComboBoxCodDewey;
    private javax.swing.JComboBox jComboBoxIdiomas6391;
    private com.toedter.calendar.JDateChooser jDateChooserFechaAdquisicion;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelFechaAdquisicion;
    private javax.swing.JLabel jLabelPaginasTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableAutores;
    private javax.swing.JTextArea jTextAreaSinopsis;
    private javax.swing.JTextField jTextFieldCodAutor;
    private javax.swing.JTextField jTextFieldCodTitulo;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNumPaginas;
    // End of variables declaration//GEN-END:variables

    // Implementacion de los metodos de 'GestionarModelo'
    @Override
    public void fijarModelo(Object object) {
        this.titulo = (Titulo) object;  //Readaptar el objeto mediante DowCasting para hacerlo un titulo

        setTitle("Ficha título: " + titulo.getNombreTitulo()); //Fija el titulo apartir de NombreTitulo
        jComboBoxCodDewey.setSelectedItem(titulo.getDewey());//Fija los datos de CategoriaDewey marcandolo el elegido
        jComboBoxIdiomas6391.setSelectedItem(titulo.getIdioma6391());//Fija los datos de CategoriaDewey marcandolo el elegido

        jTextFieldCodAutor.setText(titulo.getId().getIdApellido());
        jTextFieldCodTitulo.setText(titulo.getId().getIdTitulo());
        jTextFieldNombre.setText(titulo.getNombreTitulo());
        jTextAreaSinopsis.setText(titulo.getSinopsis());

        autoresTableModel = new AutoresTableModel(titulo.getAutors());
        jTableAutores.setModel(autoresTableModel);

        try {
            jTextFieldNumPaginas.setText(titulo.getNumPaginas().toString());
        } catch (NullPointerException nEx) {
            jTextFieldNumPaginas.setText("???");//Aviso de que viene nulo de datos
        }
        jDateChooserFechaAdquisicion.setDate(titulo.getFechaAdquisicion());//Especifica y fija la fecha en JDchooser


    }

    @Override
    public Object obtenerModelo() {
        return titulo;
    }

    @Override
    public void limpiarModelo() {
        titulo = null;

        jComboBoxCodDewey.setSelectedIndex(0);

        jTextFieldCodAutor.setText("");
        jTextFieldCodTitulo.setText("");
        jTextFieldNombre.setText("");
        jTextAreaSinopsis.setText("");
        autoresTableModel = new AutoresTableModel(3);
        jTableAutores.setModel(autoresTableModel);
        jTextFieldNumPaginas.setText("");
        this.jDateChooserFechaAdquisicion.setDate(null);
    }

    @Override
    public void setEditable(boolean esEditable) {
        //jTextFieldCodDewey.setEditable(setEditable);
        jTextFieldCodAutor.setEditable(esEditable);
        jTextFieldCodTitulo.setEditable(esEditable);
        jTextFieldNombre.setEditable(esEditable);
        jTextFieldNombre.setEditable(esEditable);
        jTextAreaSinopsis.setEditable(esEditable);
        autoresTableModel.setEditable(esEditable);
        jComboBoxCodDewey.setEnabled(esEditable);
        jTextFieldNumPaginas.setEditable(esEditable);
        jDateChooserFechaAdquisicion.setEnabled(esEditable);
    }

    @Override
    public void modelPropertyChange(PropertyChangeEvent evt) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void procesarEvento(Evento evento) {
        TituloId tituloId = ((Titulo) evento.getInfo()).getId();

        switch (evento.getTipoEvento()) {
            case ALTA_TITULO_OK:
                JOptionPane.showMessageDialog(this,
                        "Alta Ok: " + tituloId,
                        "Alta título",
                        JOptionPane.OK_OPTION);
                setVisible(false);
                if (getDelegado() != null) {
                    getDelegado().procesarEvento(new Evento(TipoEvento.ALTA_ELEMENTO_OK, (Titulo) evento.getInfo()));
                }
                break;
            case ALTA_TITULO_ERROR:
                JOptionPane.showMessageDialog(this,
                        "Alta error: " + tituloId,
                        "Alta título",
                        JOptionPane.ERROR_MESSAGE);
                break;

            case MODIFICACION_TITULO_OK:
                JOptionPane.showMessageDialog(this,
                        "Modificacion Ok: " + tituloId,
                        "Modificacion título",
                        JOptionPane.INFORMATION_MESSAGE);
                setVisible(false);
                if (getDelegado() != null) {
                    getDelegado().procesarEvento(new Evento(TipoEvento.MODIFICACION_ELEMENTO_OK, (Titulo) evento.getInfo()));
                }
                break;
            case MODIFICACION_TITULO_ERROR:
                JOptionPane.showMessageDialog(this,
                        "Modificacion error: " + tituloId,
                        "Modificacion título",
                        JOptionPane.ERROR_MESSAGE);
                break;
            case BAJA_TITULO_OK:
                tituloId = ((Titulo) evento.getInfo()).getId();
                JOptionPane.showMessageDialog(this,
                        "Baja de título correcta",
                        "Baja de titulo: " + tituloId.getDeweyCategoriaDewey() + "-" + tituloId.getIdApellido() + "-" + tituloId.getIdTitulo(),
                        JOptionPane.INFORMATION_MESSAGE);
                //tableModel.borrarInfo(tituloId);
                setVisible(false);
                if (getDelegado() != null) {
                    getDelegado().procesarEvento(new Evento(TipoEvento.BAJA_ELEMENTO_OK, (Titulo) evento.getInfo()));
                }
                break;
            case BAJA_TITULO_ERROR:
                tituloId = ((Titulo) evento.getInfo()).getId();
                JOptionPane.showMessageDialog(this,
                        "Error en baja de título",
                        "Baja de titulo: " + tituloId.getDeweyCategoriaDewey() + "-" + tituloId.getIdApellido() + "-" + tituloId.getIdTitulo(),
                        JOptionPane.ERROR_MESSAGE);
                break;
            default:
                throw new AssertionError("Evento no controlado");
        }

    }

    @Override
    public void setModo(String modo) {

        this.modo = modo;

        if (modo.equals("mostrar")) {
            setTitle("Consulta título");
            this.setEditable(false);
            this.jDateChooserFechaAdquisicion.setEnabled(false);
            this.jButtonAceptar.setText("Aceptar");
            jButtonCancelar.setVisible(false);
        } else if (modo.equals("alta")) {
            limpiarModelo();
            setEditable(true);
            setTitle("Alta de título");
            this.jButtonAceptar.setText("Alta");
            jButtonCancelar.setVisible(true);
        } else if (modo.equals("baja")) {
            setTitle("Baja título");
            this.setEditable(false);
            this.jDateChooserFechaAdquisicion.setEnabled(false);
            this.jButtonAceptar.setText("Baja");
            jButtonCancelar.setVisible(true);
        } else if (modo.equals("modificar")) {
            setEditable(true);
            setTitle("Modificación de título");
            this.jComboBoxCodDewey.setEnabled(false);
            this.jTextFieldCodAutor.setEditable(false);
            this.jTextFieldCodTitulo.setEditable(false);
            this.jTextFieldNombre.setEditable(false);
            this.jTextFieldNumPaginas.setEditable(true);
            this.jDateChooserFechaAdquisicion.setEnabled(true);
            this.jButtonAceptar.setText("Modificar");
            jButtonCancelar.setVisible(true);
        }
    }

    @Override
    public void fijarModelo(Collection object) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public BaseTableModelGen obtenerModeloGen() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    class AutoresTableModel extends DefaultTableModel {

        boolean editable = true;
        Object[] encabezado = {"Apellidos", "Nombre"};
        private Set<Autor> autores = new HashSet<Autor>();

        /*
         * Construye un modelo para la vista de la tabla de autores con "filas"
         * vacias
         */
        public AutoresTableModel(int filas) {
            super();

            Object data[][] = new Object[filas][encabezado.length];

            for (int i = 0; i < filas; i++) {
                for (int j = 0; j < encabezado.length; j++) {
                    data[i][j] = null;
                }
            }

            setDataVector(data, encabezado);
        }

        /*
         * Construye un modelo para la vista de la tabla de autores con los "autores"
         */
        public AutoresTableModel(Set<Autor> autores) {

            super();
            this.autores = autores;
            Object data[][] = new Object[autores.size()][encabezado.length];

            int i = 0;
            String apellidos = "";
            for (Autor autor : autores) {
                // Extraemos los apellidos
                apellidos += autor.getApellido1Autor() == null ? "" : autor.getApellido1Autor();
                apellidos += autor.getApellido2Autor() == null ? "" : " " + autor.getApellido2Autor();
                data[i][0] = apellidos;

                // Extraemos el nombre
                data[i][1] = autor.getNombreAutor() == null ? "SIN AUTOR" : autor.getNombreAutor();
                i++;
            }

            setDataVector(data, encabezado);
        }

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            if (!editable) {
                return false;
            } else {
                return super.isCellEditable(rowIndex, columnIndex);
            }
        }

        public void addAutor(Autor autor) {
            autores.add(autor);
        }

        public boolean isEditable() {
            return editable;
        }

        public void setEditable(boolean editable) {
            System.out.println("editable:" + editable);
            this.editable = editable;
        }
    }
}
