/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VistaGFichaAutor.java
 *
 * Created on 27-dic-2011, 12:11:35
 */
package Vista.Nivel2;

import Controlador.Controlador;
import Controlador.Evento;
import HBM.Autor;
import Vista.Modelos.BaseTableModelGen;
import java.beans.PropertyChangeEvent;
import java.util.Collection;
import javax.swing.JOptionPane;

/**
 *
 * @author Mañana
 */
public class VistaGFichaAutor extends FichaGBase {

    private Controlador controlador;
    private String modo;
    private Autor autor;

    /** Creates new form VistaGFichaAutor */
    public VistaGFichaAutor(Controlador controlador) {
        initComponents();
        this.controlador = controlador;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldAutorId = new javax.swing.JTextField();
        jTextFieldAutorNombre = new javax.swing.JTextField();
        jTextFieldAutorApellido1 = new javax.swing.JTextField();
        jTextFieldAutorApellido2 = new javax.swing.JTextField();
        jButtonAutorAceptar = new javax.swing.JButton();
        jButtonAutorCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jDateChooserAutorFechaNacimiento = new com.toedter.calendar.JDateChooser("dd/MM/yyyy", "##/##/####",'_');
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jDateChooserAutorFechaDefuncion = new com.toedter.calendar.JDateChooser("dd/MM/yyyy","##/##/####",'_');

        setTitle("Autor");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_info_16.png"))); // NOI18N

        jLabel1.setText("ID");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido 1");

        jLabel4.setText("Apellido 2");

        jTextFieldAutorId.setColumns(3);

        jTextFieldAutorNombre.setColumns(15);

        jTextFieldAutorApellido1.setColumns(15);

        jTextFieldAutorApellido2.setColumns(15);

        jButtonAutorAceptar.setText("Aceptar");
        jButtonAutorAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAutorAceptarActionPerformed(evt);
            }
        });

        jButtonAutorCancelar.setText("Cancelar");

        jLabel6.setText("Fecha Nacimiento");

        jLabel7.setText("Fecha Defunción");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jDateChooserAutorFechaDefuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDateChooserAutorFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonAutorAceptar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonAutorCancelar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldAutorApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldAutorApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldAutorId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldAutorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldAutorId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldAutorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldAutorApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldAutorApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooserAutorFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserAutorFechaDefuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAutorAceptar)
                    .addComponent(jButtonAutorCancelar))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAutorAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAutorAceptarActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonAutorAceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAutorAceptar;
    private javax.swing.JButton jButtonAutorCancelar;
    private com.toedter.calendar.JDateChooser jDateChooserAutorFechaDefuncion;
    private com.toedter.calendar.JDateChooser jDateChooserAutorFechaNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextFieldAutorApellido1;
    private javax.swing.JTextField jTextFieldAutorApellido2;
    private javax.swing.JTextField jTextFieldAutorId;
    private javax.swing.JTextField jTextFieldAutorNombre;
    // End of variables declaration//GEN-END:variables

    @Override
    public void fijarModelo(Object object) {
        autor = (Autor) object;
        setTitle("Ficha Autor: " + autor.getNombreAutor());
        //fijamos los campos utilizando el toString cuando sea un char o Int
        jTextFieldAutorId.setText(autor.getIdAutor().toString());
        jTextFieldAutorNombre.setText(autor.getNombreAutor());
        jTextFieldAutorApellido1.setText(autor.getApellido1Autor());
        jTextFieldAutorApellido2.setText(autor.getApellido2Autor());
    }

    @Override
    public Object obtenerModelo() {//Obtiene el objeto a tratar
        return autor;
    }

    @Override
    public void limpiarModelo() {//Fija los valores por defecto como campos sin datos
        autor = null;
        jTextFieldAutorId.setText("");
        jTextFieldAutorNombre.setText("");
        jTextFieldAutorApellido1.setText("");
        jTextFieldAutorApellido2.setText("");

    }

    @Override
    public void setEditable(boolean esEditable) {//Fija si va a ser editable o no
        jTextFieldAutorId.setEditable(esEditable);
        jTextFieldAutorNombre.setEditable(esEditable);
        jTextFieldAutorApellido1.setEditable(esEditable);
        jTextFieldAutorApellido2.setEditable(esEditable);

    }

    @Override
    public void setModo(String modo) {//Metodo obligatorio para todas las Fichas tanto para autor como titulo como usuario
        this.modo = modo;

        if (modo.equals("mostrar")) {//Se especifica los botones que se van a visualizar
            setTitle("Consulta Autor");
            setEditable(false);
            jButtonAutorAceptar.setText("Aceptar");
            jButtonAutorCancelar.setVisible(false);
        } else if (modo.equalsIgnoreCase("alta")) {//equalsIgnoreCase lee tanto en mayusculas como en minusculas
            limpiarModelo();
            setEditable(true);
            setTitle("Alta de Autor");
            jButtonAutorAceptar.setText("Alta");
            jButtonAutorCancelar.setVisible(true);
        } else if (modo.equals("baja")) {
            setTitle("Baja Autor");
            setEditable(false);
            jButtonAutorAceptar.setText("Baja");
            jButtonAutorCancelar.setVisible(true);
        } else if (modo.equals("modificar")) {
            setEditable(true);
            setTitle("Modificación de Autor");
            this.jTextFieldAutorId.setEnabled(false);
            this.jTextFieldAutorNombre.setEditable(false);
            this.jTextFieldAutorApellido1.setEditable(false);
            this.jTextFieldAutorApellido2.setEditable(false);
            this.jButtonAutorAceptar.setText("Modificar");
            jButtonAutorCancelar.setVisible(true);
        }
    }

    @Override
    public void modelPropertyChange(PropertyChangeEvent evt) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void procesarEvento(Evento evento) {//Dar cuerpo a los procesardor de evento
         Autor autor = (Autor) evento.getInfo();//Instanciando anteriormente los eventos en TipoEvento.java

        switch (evento.getTipoEvento()) {
            case ALTA_AUTOR_OK:
                JOptionPane.showMessageDialog(this,
                        "Alta Ok: " + autor.getIdAutor(),
                        "Alta título",
                        JOptionPane.DEFAULT_OPTION);
                setVisible(false);
                break;
                
            case ALTA_AUTOR_ERROR:
                JOptionPane.showMessageDialog(this,
                        "Alta error: " + autor.getIdAutor(),
                        "Alta título",
                        JOptionPane.ERROR_MESSAGE);
                break;

            case MODIFICACION_AUTOR_OK:
                JOptionPane.showMessageDialog(this,
                        "Modificacion Ok: " + autor.getIdAutor(),
                        "Modificacion título",
                        JOptionPane.DEFAULT_OPTION);
                setVisible(false);
                break;
                
            case MODIFICACION_AUTOR_ERROR:
                JOptionPane.showMessageDialog(this,
                        "Modificacion error: " + autor.getIdAutor(),
                        "Modificacion título",
                        JOptionPane.ERROR_MESSAGE);
                break;
                
            case BAJA_AUTOR_OK:
                JOptionPane.showMessageDialog(this,
                        "Baja de título correcta",
                        "Baja de AUTOR: " + autor.getIdAutor() + "-" + autor.getApellido1Autor()+ "-" + autor.getApellido2Autor(),
                        JOptionPane.INFORMATION_MESSAGE);
                //tableModel.borrarInfo(AUTORId);
                setVisible(false);
                break;
                
            case BAJA_AUTOR_ERROR:
                JOptionPane.showMessageDialog(this,
                        "Error en baja de título",
                        "Baja de AUTOR: " + autor.getIdAutor() + "-" + autor.getApellido1Autor()+ "-" + autor.getApellido2Autor(),
                        JOptionPane.ERROR_MESSAGE);
                break;
            default:
                throw new AssertionError("Evento no controlado");
        }
    }

    @Override
    public void fijarModelo(Collection object) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public BaseTableModelGen obtenerModeloGen() {
        throw new UnsupportedOperationException("Not supported yet.");
    }
}
